### ISSUE TITLE
FixedBoundary

### ISSUE THREAD

**Issue by dhblum** [Mathadon/modelica_MPC#6]
This issue is to create a new Fluid.Sources.FixedBoundary model.  JModelica optimization with IBPSA.Fluid.Sources.FixedBoundary results in 

```
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot convert expression to MX: fill(0.0, 0)
	at org.jmodelica.optimica.compiler.FExp.toMX(Unknown Source)
	at org.jmodelica.optimica.compiler.FExp.toMXVector(Unknown Source)
	at org.jmodelica.optimica.compiler.FFunctionCall.toMXVector(Unknown Source)
	at org.jmodelica.optimica.compiler.FFunctionCall.toMXVector(Unknown Source)
	at org.jmodelica.optimica.compiler.FFunctionCall.toMX(Unknown Source)
	at org.jmodelica.optimica.compiler.FDotMulExp.toMX(Unknown Source)
Java error occurred: 
```

This is caused by the function Modelica.Fluid.Utilities.checkBoundary.

Removing the fuction from Fluid.Sources.FixedBoundary works.  So far, attempts to inline the function have failed.

**Comment by Mathadon** [comment]
Duplicate of #7
